plugins {
    id 'java'
    id 'application'
    id 'info.solidsoft.pitest' version '1.15.0'
    id 'jacoco'
}

application {
    mainClass.set("main.Main")
}

group = 'com.t12g01.tetris'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation group: 'com.googlecode.lanterna', name: 'lanterna', version: '3.1.1'

    testImplementation 'org.mockito:mockito-core:3.7.7'
}

pitest {
    targetClasses = ['model.*', 'controller.*', 'states.*', 'view.*', 'main.*', 'music.*'] // Specify the packages to mutate
    targetTests = ['*Test'] // Specify the test classes
    threads = 4
    outputFormats = ['HTML', 'XML'] // Formats for the report
    mutators = ['ALL'] // Mutators to use; 'ALL' covers all mutation types
    junit5PluginVersion = '0.14' // Ensure compatibility with JUnit 5
    pitestVersion = '1.9.11' // Specify PITest version
    timestampedReports = false // Generate reports in a consistent directory
    verbose = true
    jvmArgs = ['-Dfile.encoding=UTF-8'] // Force UTF-8 encoding
}
jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType(JavaCompile) {
    compileJava {
        options.encoding = "UTF-8"
    }
    compileTestJava {
        options.encoding = "UTF-8"
    }
}

    test {
        useJUnitPlatform()
    }
