plugins {
    id 'java'
    id 'application'
    id 'info.solidsoft.pitest' version '1.9.11'
    id 'jacoco'
}

application {
    mainClass.set("main.Main")
}

group = 'com.t12g01.tetris'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5 dependencies
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.10.0'
    testImplementation 'org.junit.platform:junit-platform-engine:1.10.0'

    // Lanterna dependency
    implementation 'com.googlecode.lanterna:lanterna:3.1.1'

    // Mockito for mocking
    testImplementation 'org.mockito:mockito-core:5.0.0'

    // Pitest JUnit 5 Plugin
    testImplementation 'org.pitest:pitest-junit5-plugin:1.2.0'
}

pitest {
    targetClasses = ['model.*', 'controller.*', 'states.*', 'view.*', 'main.*', 'music.*']
    targetTests = ['*Test'] // Ensure your test class names match this pattern
    threads = 4
    outputFormats = ['HTML', 'XML']
    pitestVersion = '1.14.4'
    mutators = ['ALL']
    junit5PluginVersion = '1.2.0'
    timestampedReports = false
    verbose = true
    jvmArgs = ['-Dfile.encoding=UTF-8']
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
